name: 'TSFFS fuzzing action'
description: 'Run TSFFS on target project'
inputs:
  timeout:
    description: 'Default time to run for (24h)'
    required: false
    default: '1440'
outputs:
  results:
    description: 'placeholder'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: docker login --username ${{ secrets.DOCKER_USER }} --passwrdo ${{ secrets.DOCKER_PAT }}
    - shell: bash
      run: docker pull tklengyel:tsffs
    - shell: bash
      run: docker run -v $PWD:/github/workspace tklengyel:tsffs -t ${{ inputs.timeout }}
