name: 'TSFFS fuzzing action'
description: 'Run TSFFS on target project'
inputs:
  timeout:
    description: 'Default time to run for (24h)'
    required: false
    default: '1440'
  user:
    required: false
  password:
    required: false
outputs:
  results:
    description: 'placeholder'
runs:
  using: 'composite'
  steps:
    - shell: bash
      if: ${{ inputs.user }} != ''
      run: echo ${{ inputs.password }} | docker login --username ${{ inputs.user }} --password-stdin
    - shell: bash
      run: docker pull tklengyel:tsffs
    - shell: bash
      run: docker run -v $PWD:/github/workspace tklengyel:tsffs -t ${{ inputs.timeout }}
