name: 'TSFFS fuzzing action'
description: 'Run TSFFS on target project'
inputs:
  timeout:
    description: 'Default time to run for (24h)'
    required: false
    default: '1440'
outputs:
  results:
    description: 'placeholder'
runs:
  using: 'docker'
  image: 'Dockerfile.action'
  credentials:
    username: ${{ secrets.DOCKER_USER }}
    password: ${{ secrets.DOCKER_PAT }}
  args:
    - '-t'
    - ${{ inputs.timeout }}
