name: Test running TSFFS as Github Action
on:
  push:
jobs:
  tsffs:
    runs-on: ubuntu-latest
    steps:
      - uses: tklengyel/tsffs@github_action
        with:
          timeout: 360
          user: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
